### PR TITLE
[bugfix] Pass ctx in useActivePlugins

### PR DESCRIPTION
**Pull request by kaixi-wang**
## 🔗 Related Issues

  Fixes a regression introduced in commit 9bac5966c5, "add accessors / docstrings" that:                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                          
  1. Crashes where useActivePlugins runs without fos.dataset available (e.g. routes that don't preload the dataset page query like the runs page in teams).  
```
pageQueryReader is not a function

../../../app/packages/relay/src/Writer.tsx (55:1) @ getPageQuery


  53 | export function getPageQuery<T extends OperationType>() {
  54 |   return { pageQuery: pageQueryReader<T>(), subscribe };
> 55 | }
     | ^
  56 |
  57 | /**
  58 |  * Effect for restting an atom's value when the view or dataset changes.
Call Stack
29

Show 22 ignore-listed frame(s)
getPageQuery
../../../app/packages/relay/src/Writer.tsx (55:1)
eval
../../../app/packages/relay/src/graphQLSyncFragmentAtom.ts (52:26)
Module.useCurrentDataset
../../../app/packages/state/src/accessors/dataset.ts (38:1)
useGetDefaultPluginCtx
packages/plugins/src/index.ts (269:19)
useActivePlugins
packages/plugins/src/index.ts (285:31)
useCustomComponents
packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx (62:21)
DynamicIO
packages/core/src/plugins/SchemaIO/components/DynamicIO.tsx (19:28)
1
```

  2. Wastes dataset/schema recoil subscriptions on every call site, even those that pass their own ctx and never read the default values. In schema-driven UIs (DynamicIO is invoked once per node) this fan-out adds dozens of unnecessary subscribers per dialog, all re-rendering on  every dataset/schema mutation.   

## 📋 What changes are proposed in this pull request?

-   Make ctx required at the type level on useActivePlugins and usePluginComponent. Remove useGetDefaultPluginCtx entirely. The hook now reads no recoil state of its own; the caller is the only place that can supply ctx.                                                                

## 🧪 How is this patch tested? If it is not, please explain why.

- added tests
- verified by running app locally 

## 📝 Release Notes

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

<!--
If answering "yes" above:
Details in 1-2 sentences. You can refer to another PR with a description
if this PR is part of a larger change.

If answering "no" above, leave empty or add "N/A"
-->

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other


<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **Refactor**
  * Centralized plugin registry and moved plugin APIs to a single registry module; plugin activation now uses an explicit, memoized activator context (dataset/schema) for consistent behavior.

* **Bug Fixes**
  * Ensured missing-panel/component lookup always receives an explicit options object to avoid inconsistent resolution.

* **Tests**
  * Added tests covering plugin registration and activation hooks, ctx handling, and runtime filtering to improve reliability.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

### CODE REVIEW

**Review by sashankaryal — APPROVED** [review]
nit: would have liked to see the refactor of moving registry to a new module in a different PR and for this PR to only contain the fix.

I did local testing with custom grid renderer plugins and everything looked good. Thanks for addressing it! 🚀
